analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: México
  adjective: México
create_goals:
  previous_next_links: true
  goals: []
create_indicators:
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
decimal_separator: '.'
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Lorem ipsum
    content: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_short
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: custom
graph_color_list: ['3fd64f','cfd63f','4eecec','ec4ed9']
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - es
  - en
languages_public: []
logos: []
map_layers: 
  -
    # The subfolder under 'geojson' in the data repository holding the GeoJSON files:
    subfolder: map/entidades-federativas
    # The label to use in the "Download GeoJSON" button:
    label: indicator.map
    # The minimum zoom at which this layer should be visible.
    # For example, if this "min_zoom" is set to 4, then this
    # layer will be invisible at zoom level 3 or less.
    min_zoom: 0
    # The maximum zoom at which this layer should be visible.
    # For example, if this "max_zoom" is set to 8, then this
    # layer will be invisible at zoom level 9 or more.
    max_zoom: 6
    # Whether or not these boundaries should display statically
    # on lower layers.
    staticBorders: true
  -
    # The subfolder under 'geojson' in the data repository holding the GeoJSON files:
    subfolder: map/municipios
    # The label to use in the "Download GeoJSON" button:
    label: indicator.map
    # The minimum zoom at which this layer should be visible.
    # For example, if this "min_zoom" is set to 4, then this
    # layer will be invisible at zoom level 3 or less.
    min_zoom: 7
    # The maximum zoom at which this layer should be visible.
    # For example, if this "max_zoom" is set to 8, then this
    # layer will be invisible at zoom level 9 or more.
    max_zoom: 20
    # Whether or not these boundaries should display statically
    # on lower layers.
    staticBorders: false
map_options:
  disaggregation_controls: true
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: myMapColorFunction
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
 # Genera la pestaña de fuentes con la etiqueta source_1, source_2... del yml de configuración (obsoleto)
  - scope: sources
    title: indicator.sources
    description: ''
  # Genera otra pestaña de fuentes con la etiqueta source del yml de configuración
  #- scope: sources_alt
  #  title: indicator.sources
  #  description: ''
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://sdg-odsmexico.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: inprogress
      label: status.statistics_in_progress
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/sdg-odsmexico/data'
repository_url_site: ''
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
