# You will need to change all of the Github-related variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"
#
# NOTE: This "production" version only contains differences from site_config_prod.yml.
#
# Whereas site_config.yml can be produced using the site configuration
# form, we recommend you manually edit this file directly.
#
# See also _config_prod.yml in the root of this repository.

environment: production
# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://sdg-prod-odsmexico.github.io/sdg-prod-data"

analytics:
  # For production, you likely want to enter a Google Analytics code below.
  gtag: G-08FYFJPRXC
  ga_prod: G-08FYFJPRXC
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
